# Scale factor
SCALE = 4

# Resolution (Game Boy Advance)
LOGICAL_WIDTH = 240
LOGICAL_HEIGHT = 160
ACTUAL_WIDTH = LOGICAL_WIDTH * SCALE
ACTUAL_HEIGHT = LOGICAL_HEIGHT * SCALE

# Tile size
LOGICAL_TILE_SIZE = 16
ACTUAL_TILE_SIZE = LOGICAL_TILE_SIZE * SCALE

# Speed
SPEED = 4