FILENAME_STATS      = "data/smt/smt_stats.json"
FILENAME_MOVES      = "data/smt/smt_moves.json"
FILENAME_HPFILL     = "hpfill.png"
FILENAME_MPFILL     = "mpfill.png"
FILENAME_MPCOSTFILL = "mpcostfill.png"
FILENAME_CURSOR     = "cursor.png"
FILENAME_HPMP       = "hpmp0.png"
FILENAME_HPMP_ENEMY = "hpmp1.png"
FILENAME_LV         = "lv.png"
FILENAME_FRAME      = "battleframe.png"
FILENAME_PBRED      = "pokeballred.png"
FILENAME_PBBLUE     = "pokeballblue.png"

PLAYER_DEX_NO = -1

FRESH_PRESS_TURNS = [2, 2, 2, 2]

STATE_MAIN                                            = 0
STATE_SKILLS                                          = 1
STATE_ITEMS                                           = 2
STATE_GUARD                                           = 3
STATE_TALK                                            = 4
STATE_CHANGE                                          = 5
STATE_ESCAPE                                          = 6
STATE_INFO                                            = 7
STATE_SKILLS_TARGET_ENEMY                             = 8
STATE_SCROLL                                          = 9
STATE_WAIT                                            = 10
STATE_ANIMATE_SKILL                                   = 11

MENU_CURSOR_SKILLS_X     = 0
MENU_CURSOR_SKILLS_Y     = 0
MENU_CURSOR_ITEMS_X      = 1
MENU_CURSOR_ITEMS_Y      = 0
MENU_CURSOR_GUARD_X      = 2
MENU_CURSOR_GUARD_Y      = 0
MENU_CURSOR_TALK_X       = 3
MENU_CURSOR_TALK_Y       = 0
MENU_CURSOR_CHANGE_X     = 0
MENU_CURSOR_CHANGE_Y     = 1
MENU_CURSOR_ESCAPE_X     = 1
MENU_CURSOR_ESCAPE_Y     = 1
MENU_CURSOR_PASS_X       = 2
MENU_CURSOR_PASS_Y       = 1
MENU_CURSOR_INFO_X       = 3
MENU_CURSOR_INFO_Y       = 1

COORDS_BACKGROUND = (0, 0)
COORDS_MENU_MAIN = [
    (65, 525), (316, 525), (536, 525), (765, 525),
    (65, 573), (316, 573), (536, 573), (765, 573)
]
COORDS_MENU_MAIN_0 = (
    (65, 525), (316, 525), (536, 525), (765, 525)
)
COORDS_MENU_MAIN_1 = (
    (65, 573), (316, 573), (536, 573), (765, 573)
)
COORDS_MENU_SKILLS = [
    (40, 470), 
    (40, 470 + 49), 
    (40, 470 + 49 + 49)
]

COLOR_WHITE = (255, 255, 255)
COLOR_MAGENTA = (255, 0, 228)
COLOR_GREEN = (0, 255, 0)
COLOR_RED = (255, 0, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_PURPLE = (255, 0, 255)
COLOR_BLACK = (0, 0, 0)

FONT0_FILENAME = "font3.png"
FONT0_WIDTH = 7
FONT0_HEIGHT = 13
FONT0_SCALE = 4
FONT0_SPACING = 28
FONT1_FILENAME = "font5.png"
FONT1_WIDTH = 7
FONT1_HEIGHT = 13
FONT1_SCALE = 3
FONT1_SPACING = 16
FONT2_FILENAME = "font4.png"
FONT2_WIDTH = 6
FONT2_HEIGHT = 13
FONT2_SCALE = 4
FONT2_SPACING = 21
FONT3_FILENAME = "font5.png"
FONT3_WIDTH = 7
FONT3_HEIGHT = 13
FONT3_SCALE = 2
FONT3_SPACING = 12

ICON_W = 24
ICON_H = 24

SCALE_PRESSTURN = 2

BACKGROUND_GRASS_1     = 0
BACKGROUND_WATER_1     = 1
BACKGROUND_CAVE_1      = 2
BACKGROUND_BRICK_1     = 3
BACKGROUND_GRASS_2     = 4
BACKGROUND_WATER_2     = 5
BACKGROUND_CAVE_2      = 6
BACKGROUND_BRICK_2     = 7
BACKGROUND_GRASS_3     = 8
BACKGROUND_CAVE_3      = 9
BACKGROUND_BRICK_4     = 10
BACKGROUND_BRICK_5     = 11
BACKGROUND_WATER_3     = 12
BACKGROUND_CAVE_4      = 13
BACKGROUND_BRICK_6     = 14

BOUNCE_AMP = 8
BOUNCE_SPEED = 0.18
BOUNCE_PHASE = 0.6

INFO_ROW_PLAYER = 0
INFO_ROW_ENEMY  = 1
INFO_ROW_NONE   = 9

SCROLL_DELAY_CONSTANT = 20
SCROLL_CONSTANT = 2

ENEMY_DRAW_ORDER = (1, 3, 0, 2)

WAIT_FRAMES_BEFORE_DAMAGE = 30

X_PKMN_PLAYER = -64
X_PKMN_ENEMY = 300 - 20
X_HPMP = 672
X_ACTIVE_POKEMON_NAME = 692
X_LV = 877
X_LV_TEXT = 902
X_HP_BAR = 748
X_MP_BAR = 748
X_BUFF = 680
X_HPMP_ENEMY = 0
X_ACTIVE_TARGET_NAME = 20
X_LV_ENEMY = 205
X_LV_TEXT_ENEMY = 230
X_HPMP_TO_FILL = 76
X_BUFF_ENEMY = 8
X_PT = 820
X_PT_ENEMY = 144
X_MENU_MAIN = 40
X_SKILLS = 80

Y_HPMP = 308
Y_HPMP_ENEMY = 0
Y_PKMN_PLAYER = 192
Y_PKMN_ENEMY = 0
Y_ACTIVE_POKEMON_NAME_OFFSET = 14
Y_LV_OFFSET = 23
Y_LV_TEXT_OFFSET = 14
Y_FRAME = 448
Y_HP_BAR = 396
Y_MP_BAR = 416
Y_BUFF = -24
Y_LV_TEXT_OFFSET_ENEMY = 14
Y_LV_OFFSET_ENEMY = 23
Y_HPMP_TO_FILL = 88
Y_HPMP_RATIO_OFFSET = 52
Y_BUFF_ENEMY = 120
Y_FRAME = 448
Y_PT = 305 - 20
Y_PT_ENEMY = 120
Y_MENU_MAIN_0 = 470
Y_MENU_MAIN_1 = 517
Y_MENU_MAIN_2 = 565
Y_SKILLS = 470
Y_SKILLS_INCR = 49

W_HP_BAR = 192
W_MP_BAR = 192

H_HP_BAR = 8
H_MP_BAR = 8

D_PKMN_PLAYER = 150 + 25
D_PKMN_ENEMY = 152
D_PLAYER_OFFSET_X = 50
D_PLAYER_OFFSET_Y = 64
D_PKMN_PLAYER_OFFSET_Y = 16
D_HPMP_RATIO_OFFSET_X = 20
D_HPMP_RATIO_OFFSET_Y = 52
D_STAT_BUFFS = 28
D_PT = 34

AFFINITY_NEUTRAL = 0
AFFINITY_RESIST = 1
AFFINITY_NULL = 2
AFFINITY_REFLECT = 9

PT_STATE_TRANSPARENT = "transparent"
PT_STATE_SOLIDBLUE   = "solid_blue"
PT_STATE_SOLIDRED    = "solid_red"
PT_STATE_FLASHBLUE   = "flash_blue"
PT_STATE_FLASHRED    = "flash_red"
PT_DURATION_FLASH    = 10

MENU_MAIN_LINE_1 = "  Skills   Item    Guard   Talk"
MENU_MAIN_LINE_2 = "  Change   Escape  Pass    Info"

MAX_OPACITY_ANIM = 100

ELEMENT_COLORS = {
    "Physical": (255, 255, 255),
    "Fire": (255, 0, 0),
    "Force": (0, 255, 0),
    "Ice": (0, 0, 255),
    "Electric": (255, 255, 0),
    "Light": (240, 255, 156),
    "Dark": (76, 0, 99)
}