FRAME_W = 240
FRAME_H = 48

PT_X = 820
PT_Y = 305 - 20
PT_SPACING = 34
PT_X_ENEMY = 144
PT_Y_ENEMY = 120

HP_BAR_HEIGHT = 8
MP_BAR_HEIGHT = 8
HP_BAR_X = 748
HP_BAR_Y = 396
HP_BAR_WIDTH = 192
MP_BAR_X = 748
MP_BAR_Y = 416
MP_BAR_WIDTH = 192

FONT0_FILENAME = "font3.png"
FONT0_WIDTH = 7
FONT0_HEIGHT = 13
FONT0_SCALE = 4
FONT0_SPACING = 28
FONT1_FILENAME = "font5.png"
FONT1_WIDTH = 7
FONT1_HEIGHT = 13
FONT1_SCALE = 3
FONT1_SPACING = 16
FONT2_FILENAME = "font4.png"
FONT2_WIDTH = 6
FONT2_HEIGHT = 13
FONT2_SCALE = 4
FONT2_SPACING = 21
FONT3_FILENAME = "font5.png"
FONT3_WIDTH = 7
FONT3_HEIGHT = 13
FONT3_SCALE = 2
FONT3_SPACING = 12

COLOR_WHITE = (255, 255, 255)
COLOR_MAGENTA = (255, 0, 228)
COLOR_GREEN = (0, 255, 0)
COLOR_RED = (255, 0, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_PURPLE = (255, 0, 255)
COLOR_BLACK = (0, 0, 0)

FILENAME_MOVES      = "data/smt/smt_moves.json"
FILENAME_STATS      = "data/smt/smt_stats.json"

FILENAME_HPFILL     = "hpfill.png"
FILENAME_MPFILL     = "mpfill.png"
FILENAME_MPCOSTFILL = "mpcostfill.png"
FILENAME_CURSOR     = "cursor.png"
FILENAME_HPMP       = "hpmp0.png"
FILENAME_HPMP_ENEMY = "hpmp1.png"
FILENAME_LV         = "lv.png"
FILENAME_PBRED      = "pokeballred.png"
FILENAME_PBBLUE     = "pokeballblue.png"
FILENAME_FRAME      = "battleframe.png"

SCALE_PRESSTURN = 2

PLAYER_BASE_X = -64
PLAYER_Y = 192
PLAYER_SPACING = 150

ENEMY_BASE_X = 300
ENEMY_Y = 0
ENEMY_SPACING = 152

PLAYER_OFFSET = 50
FRAME_Y = 448

COORDS_BACKGROUND = (0, 0)
COORDS_FRAME= (0, FRAME_Y)
COORDS_MENU_MAIN = [
    (65, 525), (316, 525), (536, 525), (765, 525),
    (65, 573), (316, 573), (536, 573), (765, 573)
]


PT_STATE_TRANSPARENT = "transparent"
PT_STATE_SOLIDBLUE   = "solid_blue"
PT_STATE_SOLIDRED    = "solid_red"
PT_STATE_FLASHBLUE   = "flash_blue"
PT_STATE_FLASHRED    = "flash_red"
PT_DURATION_FLASH    = 10

AMP = 8
SPEED = 0.18
PHASE = 0.6

ENEMY_DRAW_ORDER = [1, 3, 0, 2]

PLAYER_Y_OFFSET = 64
NORMAL_Y_OFFSET = 16

HPMP_X = 672
HPMP_Y = 328 - 20
HPMP_ENEMY_X = 0
HPMP_ENEMY_Y = 0
HPMP_TO_FILL_X = 76
HPMP_TO_FILL_Y_0 = 68 + 20
HPMP_TO_FILL_Y_1 = 88 + 20


ACTIVE_TARGET_NAME_X = 20
ACTIVE_TARGET_NAME_Y_OFFSET = 14
LV_X_ENEMY = 205
LVL_Y_OFFSET_ENEMY = 23
LV_TEXT_X_ENEMY = 230
LV_TEXT_Y_OFFSET_ENEMY = 14

ACTIVE_POKEMON_NAME_X = 692
ACTIVE_POKEMON_NAME_Y_OFFSET = 14
LV_X = 877
LV_Y_OFFSET = 23
LV_TEXT_X = 902
LV_TEXT_Y_OFFSET = 14

X_MENU_MAIN = 40
Y_MENU_MAIN_0 = 470
Y_MENU_MAIN_1 = 517
Y_MENU_MAIN_2 = 565
MENU_MAIN_LINE_1 = "  Skills   Item    Guard   Talk"
MENU_MAIN_LINE_2 = "  Change   Escape  Pass    Info"

MENU_MODE_MAIN = 0
MENU_MODE_ITEMS = 1
MENU_MODE_ITEM_INFO = 2
MENU_MODE_ITEM_USE = 3
MENU_MODE_ITEM_TARGET_SELECT = 11
MENU_MODE_GUARDING = 4
MENU_MODE_SKILLS = 5
MENU_MODE_TARGET_SELECT = 6
MENU_MODE_DAMAGING_ENEMY = 7
MENU_MODE_TALK = 8
MENU_MODE_ESCAPE = 9
MENU_MODE_SUBMENU = 10
MENU_MODE_DAMAGING_PLAYER = 12
MENU_MODE_ENEMY_DAMAGE = 13
MENU_MODE_INFO = 14

SKILLS_X = 80
SKILLS_Y = 470
SKILLS_Y_INCR = 49
COORDS_MENU_SKILLS = [
    (40, SKILLS_Y), 
    (40, SKILLS_Y + SKILLS_Y_INCR), 
    (40, SKILLS_Y + SKILLS_Y_INCR + SKILLS_Y_INCR)
]

DUMMY_TEXTS = [
    "Skills submenu placeholder",
    "Item submenu placeholder",
    "Guard submenu placeholder",
    "Talk submenu placeholder",
    "Change submenu placeholder",
    "Escape submenu placeholder",
    "Pass submenu placeholder",
    "Info submenu placeholder"
]
DUMMY_MSG = "(Press X to return)"

FRESH_PRESS_TURNS = [2, 2, 2, 2]

PLAYER_DEX_NO = -1
WRAP = 32
CONFIRM_ARROW_X = X_MENU_MAIN + 850
CONFIRM_ARROW_Y = Y_MENU_MAIN_2

WAIT_FRAMES_BEFORE_DAMAGE = 30

AFFINITY_NEUTRAL = 0
AFFINITY_RESIST = 1
AFFINITY_NULL = 2
AFFINITY_REFLECT = 9

AFFINITY_TEXT_WEAK = "It's super effective!"
AFFINITY_TEXT_RESIST = "It's not very effective..."
AFFINITY_TEXT_NULL = "But it had no effect!"
AFFINITY_TEXT_REFLECT = "But it was reflected back!"

NULL = 0
FLASH = 1
SOLID = 2
PRESS_TURN_HALF = 1
PRESS_TURN_FULL = 2
PRESS_TURN_WIPE = -1

MENU_INDEX_SKILLS = 0
MENU_INDEX_ITEMS = 1
MENU_INDEX_GUARD = 2
MENU_INDEX_TALK = 3
MENU_INDEX_CHANGE = 4
MENU_INDEX_ESCAPE = 5
MENU_INDEX_PASS = 6
MENU_INDEX_INFO = 7

SCROLL_CONSTANT = 2

TALK_TEXT = "The Pokemon are crazed for battle!"
ESCAPE_TEXT = "You are unable to escape!"

X_ITEM = 80
Y_ITEM = 470
ITEM_ROWS = 3
ITEM_COLS = 3
ITEM_ROW_SIZE = 49
ITEM_COL_SIZE = 290

DAMAGE_TEXT_INCR = 47

HPMP_RATIO_Y_OFFSET = 52   # or whatever roughly lands in the new empty row

BUFF_X = HPMP_X + 8
BUFF_Y = -24
BUFF_X_ENEMY = 8
BUFF_Y_ENEMY = 120
BUFF_SPACING = 28

CRIT_CHANCE = 1